Repository mesosphere/d2iq-daggers, pull requests merged in 2022-11, with the labels that each got.

#10 feat: add dagger svu
  dagger/svu/dagger.go
  dagger/svu/options.go
Labels: feature

#15 fix: Remove redundant dagger client creation
  mage/precommit/mage.go
  mage/svu/mage.go
Labels: fix

#17 feat: Add logger support
  .gitignore
  dagger/logger/doc.go
  dagger/logger/logger.go
  go.mod
  go.sum
  mage/precommit/mage.go
  mage/svu/mage.go
Labels: feature

#18 feat: Add configuration options to svu via env
  mage/precommit/mage.go
  mage/svu/mage.go
Labels: feature

#19 feat: Add help targets for mage
  mage/help/doc.go
  mage/help/help.go
  mage/precommit/mage.go
Labels: feature

#21 fix: Use correct package name for mage/svu
  mage/svu/mage.go
Labels: fix

#23 fix: Print command output if mage is not running in verbose mode
  dagger/precommit/dagger.go
  mage/precommit/mage.go
Labels: fix

#27 chore: add missing godocs
  .golangci.yml
  dagger/logger/logger.go
  dagger/options/container_customizer.go
  dagger/precommit/dagger.go
  dagger/precommit/options.go
  dagger/svu/dagger.go
  dagger/svu/options.go
  mage/precommit/mage.go
  mage/svu/mage.go
  utils/hash.go
Labels: ignore-for-release

#28 feat: add WithMountedGoCache dagger option
  dagger/common/cache.go
  dagger/common/common.go
  dagger/common/doc.go
  dagger/options/container_customizer.go
  dagger/precommit/dagger.go
  utils/hash.go
Labels: feature

#30 fix: Use verbose logging always to see precommit output.
  mage/precommit/mage.go
Labels: fix

#32 feat: Add asdf mage targets
  mage/asdf/asdf.go
  mage/asdf/doc.go
  mage/asdf/mage.go
Labels: feature

#33 feat: Add goreleaser mage package
  mage/goreleaser/build/doc.go
  mage/goreleaser/build/mage.go
  mage/goreleaser/build/option.go
  mage/goreleaser/cli/cli.go
  mage/goreleaser/cli/doc.go
  mage/goreleaser/release/doc.go
  mage/goreleaser/release/mage.go
  mage/goreleaser/release/option.go
Labels: feature

#35 fix: remove unnecessary error check
  mage/precommit/mage.go
Labels: fix

#36 fix: correct spelling in typo
  dagger/common/cache.go
Labels: fix

#40 feat: Introduce go tests
  .github/workflows/test.yaml
  hack/mage
  mage.go
  magefile.go
Labels: feature

#38 feat: Add github-cli dagger package
  dagger/githubcli/dagger.go
  dagger/githubcli/doc.go
  dagger/githubcli/options.go
Labels: feature

#43 feat: introduce dagger/golang
  .github/workflows/test.yaml
  .gitignore
  dagger/golang/dagger.go
  dagger/golang/doc.go
  dagger/golang/options.go
  magefile.go
Labels: feature
